// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SGSX.Exploria.Application.Data;

#nullable disable

namespace SGSX.Exploria.Application.Migrations
{
    [DbContext(typeof(WeatherDatabaseContext))]
    partial class WeatherDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SGSX.Exploria.Application.Models.WeatherReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("VARBINARY(MAX)");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("DATETIME2(3)");

                    b.HasKey("Id");

                    b.HasIndex("ReportDate")
                        .HasDatabaseName("IX_Dbo_WeatherReport(ReportDate)");

                    b.ToTable("WeatherReport", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
